version: '3'
services:
  python_env:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-python
    container_name: python_env
    tty: true
    stdin_open: true
    #ports:
      #- "5000:5000"
    #Developer use    
    volumes:
      #- ./web:/app/
      - ./work_project:/app/
    #command:
      #- app.py
  jupyter:
    build:
      context: ./dockerfile
      dockerfile: dockerfile-jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - "8888:8888"
      - "5000:5000"
    command: start-notebook.sh --NotebookApp.token=''
    volumes:
      #- ./jupyter:/home/jovyan/work
      - ./work_project:/home/jovyan/work
  MYSQL:
    image: mysql:8.0
    container_name: MYSQL
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aabb1234
    volumes:
      - ./mysql_data:/var/lib/mysql
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    volumes:
      - ./mongodb:/data/db
    restart: always
    expose:
      - 6016
    ports:
      - "27017:27017"
  adminmongo:
    image: mrvautin/adminmongo
    container_name: adminmongo
    hostname: adminmongo
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0